image: python2.7
services:
  - mysql
  - postgres
script:
  - sudo apt-get install socat
  - pip install -r requirements.txt --use-mirrors
  - DATABASE_URL="sqlite://:memory:" coverage run manage.py test
  - psql -c 'create database test_djangodb;' -U postgres
  - DATABASE_URL="postgres://postgres@localhost/test_djangodb" coverage run manage.py test
  - mysql -u root -e 'create database test_djangodb;'
  - DATABASE_URL="mysql://root@localhost/test_djangodb" coverage run manage.py test
