language: python
python:
  - "2.7"
  - "pypy"
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install coveralls --use-mirrors"
env:
  - DATABASE_URL="sqlite://:memory:"
  - DATABASE_URL="postgres://postgres@127.0.0.1/test_db"
script:
  - "coverage run manage.py test"
after_success:
  - "coveralls"
