language: python
python:
  - "2.7"
  - "pypy"
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install coveralls --use-mirrors"
env:
  - DB="sqlite" DATABASE_URL="sqlite://:memory:"
  - DB="pgsql"  DATABASE_URL="postgres://postgres@127.0.0.1/test_djangodb"
before_script:
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS test_djangodb;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE test_djangodb;' -U postgres; fi"
script:
  - "coverage run manage.py test"
after_success:
  - "coveralls"
