language: python
python:
  - "2.7"
# PyPy 1.9.0 on Travis is too old.
# https://github.com/travis-ci/travis-ci/issues/1106
#  - "pypy"
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install coveralls --use-mirrors"
env:
  - DB="sqlite" DATABASE_URL="sqlite://:memory:"
  - DB="pgsql"  DATABASE_URL="postgres://postgres@127.0.0.1/test_djangodb"
  - DB="mysql"  DATABASE_URL="mysql://travis@127.0.0.1/test_djangodb"
before_script:
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE test_djangodb;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then pip install MySQL-python ; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE test_djangodb;' ; fi"
script:
  - "coverage run manage.py test"
after_success:
  - "coveralls"
